fix(_document.tsx): fixed Flickering UI
vyper-protocol/vyper-otc-ui pull request #112
Opened 2022-10-05 05:40 UTC by Shikhar15606

The change fixes the flickering problem for all the pages. It extracts the evergreen styles and adds them to the HTML of the web page

fix #78

2022-10-05 15:09 UTC, GnosisAssembler requested changes
Looks really good. Very good job, figuring out how to use the `hydrationScript` from `evergreen`, with `Next.js`.

2022-10-05 15:09 UTC, GnosisAssembler commented on src/pages/_document.tsx
> +export default class MyDocument extends Document<{css: any, hydrationScript:any}> {
A small detail. Can we change the name to a more meaningful one? Like `NextDocument` for example.

2022-10-05 17:39 UTC, Shikhar15606 commented on src/pages/_document.tsx
> +export default class MyDocument extends Document<{css: any, hydrationScript:any}> {
Ya Sure, ```NextDocument``` seems good.

2022-10-05 21:00 UTC, GnosisAssembler approved these changes

2022-10-06 07:35 UTC, thegreat-vanderlinde approved these changes

2022-10-06 07:35 UTC, merged