fix(topbar.tsx): topBar UI Fixes
vyper-protocol/vyper-otc-ui pull request #137
Opened 2022-10-07 04:07 UTC by Shikhar15606

tracking the active tab in the navbar menu along with a few bug fixes

fix #120

2022-10-07 13:30 UTC, thegreat-vanderlinde requested changes
this is not working as intended

https://user-images.githubusercontent.com/91868385/194565291-396181ce-3241-4e83-a68f-6276ed1fc7ad.mov

2022-10-07 13:30 UTC, thegreat-vanderlinde commented on src/components/organisms/TopBar/TopBar.tsx
> +					<div className={activeNavItem === 1 ? cn(styles.item, styles.active) : cn(styles.item)} onClick={()=> setActiveNavItem(1)}>
we should listen on URL changes instead of setting the active route programmatically, we can have multiple ways to change routes apart from the TopBar links.

2022-10-10 15:17 UTC, thegreat-vanderlinde approved these changes
lgtm

2022-10-10 15:17 UTC, thegreat-vanderlinde commented
@Shikhar15606 now PR looks fine, can you please fix conflicts?

2022-10-10 16:21 UTC, Shikhar15606 commented
@thegreat-vanderlinde Conflicts Resolved

2022-10-10 16:36 UTC, Shikhar15606 commented
Let me add the explorer page in the navbar as well

2022-10-11 14:45 UTC, Shikhar15606 commented
Ya, sure

2022-10-11 14:57 UTC, thegreat-vanderlinde approved these changes

2022-10-11 14:57 UTC, merged