fix: check Token Amount and Disable the button
vyper-protocol/vyper-otc-ui pull request #165
Opened 2022-10-12 12:06 UTC by Shikhar15606

check Token Amount and Disable the button

fix #136

2022-10-12 12:36 UTC, Shikhar15606 commented
Hi @thegreat-vanderlinde There is still one issue in this PR: The tooltip with the message "Not enough tokens" is not working as I expect. I looked at the evergreen UI docs: https://evergreen.segment.com/components/tooltip#conditionally_show_tooltip
and set the isShown to undefined, when we do not have enough tokens, but still, the tooltip is not appearing.

2022-10-12 13:05 UTC, thegreat-vanderlinde requested changes

2022-10-12 13:05 UTC, thegreat-vanderlinde commented on src/components/organisms/actionButtons/DepositButton.tsx
> +	}, [connection, wallet.publicKey, isBuyer, rateStateQuery.data.buyerDepositAmount, rateStateQuery.data.sellerDepositAmount]);
the amount needed can be moved outside the checK:
```ts
const amountNeeded = isBuyer ? rateStateQuery.data.buyerDepositAmount : rateStateQuery.data.sellerDepositAmount
```
so the method (and the dependencies) will be lighter

2022-10-12 13:05 UTC, thegreat-vanderlinde commented on src/components/organisms/actionButtons/DepositButton.tsx
> +		const res = await checkTokenAmount(connection, wallet.publicKey, new PublicKey('7XSvJnS19TodrQJSbjUR6tEGwmYyL1i9FX7Z5ZQHc53W'), isBuyer ? rateStateQuery.data.buyerDepositAmount : rateStateQuery.dat
we cannot hard code the mint needed here. it's available in otcState object

2022-10-12 13:05 UTC, thegreat-vanderlinde commented on src/components/atoms/ButtonPill/ButtonPill.tsx
> +		</Tooltip>
the ButtonPill component it's a reusable component, we can't hardcode a logic so specific like `if disable show "not enough tokens"`. This will make the component hardly reusable in the future.

Please leave this logic in the parent component.

2022-10-14 12:23 UTC, Shikhar15606 commented
Hi, @thegreat-vanderlinde I just pushed the requested changes. The tooltip is still not working :pensive:

2022-10-17 13:47 UTC, Shikhar15606 commented
@thegreat-vanderlinde PTAL

2022-10-18 16:37 UTC, Shikhar15606 commented on src/utils/solanaHelper.ts
> +}
Ya, I fixed that

2022-10-18 16:37 UTC, Shikhar15606 commented on src/components/organisms/actionButtons/DepositButton.tsx
> +	}, [connection, wallet.publicKey, isBuyer, rateStateQuery.data.buyerDepositAmount, rateStateQuery.data.sellerDepositAmount]);
Ya sure, I fixed that

2022-10-18 16:37 UTC, Shikhar15606 commented on src/components/atoms/ButtonPill/ButtonPill.tsx
> +		</Tooltip>
Ya sure, I fixed that

2022-10-18 16:51 UTC, Shikhar15606 commented
Resolved the merge conflicts

2022-11-08 15:59 UTC, Shikhar15606 commented
@thegreat-vanderlinde I just resolved the merge conflicts

2022-11-16 08:10 UTC, thegreat-vanderlinde approved these changes
lgtm

2022-11-16 08:11 UTC, merged