[19] Create basic nav routing
vyper-protocol/vyper-otc-ui pull request #26
Opened 2022-09-14 11:41 UTC by GnosisAssembler

- Add menu items
- Create basic routing

2022-09-15 16:10 UTC, thegreat-vanderlinde requested changes

2022-09-15 16:10 UTC, thegreat-vanderlinde commented on components/organisms/TopBar/TopBar.tsx
> +							</Link>
this seems appending the url to the current path.

the wrong behavior occurs on clicking the menu when the user is already on the contract summary page:
`http://localhost:3000/contract/summary/contract/summary/WD2TKRpqhRHMJ92hHndCZx1Y4rp9fPBtAAV3kzMYKu3`

2022-09-15 16:22 UTC, GnosisAssembler commented on components/organisms/TopBar/TopBar.tsx
> +							</Link>
Yea ik. I'll find a fix for that. Typically it does not make sense to happen, but i guess it has something to do with how Next.js handles the routes

2022-09-16 13:24 UTC, thegreat-vanderlinde approved these changes
lgtm

2022-09-16 13:24 UTC, merged