249 - hide the claim button after token transfer
vyper-protocol/vyper-otc-ui pull request #278
Opened 2022-10-28 07:21 UTC by Shikhar15606

Added a listener to listen for token transfer and hide the claim button as soon as the transfer is completed.

fix #249

2022-10-28 08:56 UTC, thegreat-vanderlinde requested changes

2022-10-28 08:56 UTC, thegreat-vanderlinde commented on src/components/organisms/actionButtons/ClaimButton.tsx
> +		}
let's add these account in the ChainOtcState class as suggested on discord

2022-10-28 11:35 UTC, Shikhar15606 commented
@thegreat-vanderlinde I just refactored the code as suggested above. PTAL

2022-11-08 15:10 UTC, thegreat-vanderlinde approved these changes

2022-11-08 15:10 UTC, merged