302 - Add token logo in contract summary page
vyper-protocol/vyper-otc-ui pull request #308
Opened 2022-11-09 15:31 UTC by stevenhansel

![Screen Shot 2022-11-09 at 22 29 56](https://user-images.githubusercontent.com/54180475/200871828-a9bf65ed-2c1a-4f2e-b769-7c7a43da31c8.png)

I added the token logo in the collateral section. I also added some information about the token to make it not empty. I'm open for discussion on other solutions for the placement of the token logo itself.

2022-11-11 10:52 UTC, vantessel commented
Looks good but now we are showing the same info three times. I would show the symbol + top detail ("cUSDC") next to the amounts 

We can even make it clickable linking to the explorer, e.g. https://solscan.io/token/993dVFL2uXWYeoXuEBFXR4BijeXdTv4s6BzsCjJZuwqk

2022-11-14 03:29 UTC, stevenhansel commented
> https://solscan.io/token/993dVFL2uXWYeoXuEBFXR4BijeXdTv4s6BzsCjJZuwqk

This is a really good comparison. I'll make the changes ASAP

2022-11-14 10:45 UTC, stevenhansel commented
![Screen Shot 2022-11-14 at 17 45 27](https://user-images.githubusercontent.com/54180475/201640773-433fc473-f6c1-4628-b16d-1b55b5163f23.png)

This is the latest update, let me know what you think, thanks @vantessel

2022-11-14 11:35 UTC, vantessel commented
Looks good!

2022-11-14 12:26 UTC, vantessel commented
only thing, can we pls make it clickable to the explorer? The url can have the form of https://solscan.io/token/{token_mint}, e.g. https://solscan.io/token/993dVFL2uXWYeoXuEBFXR4BijeXdTv4s6BzsCjJZuwqk for cUSDC @stevenhansel

2022-11-14 12:57 UTC, stevenhansel commented
> only thing, can we pls make it clickable to the explorer? The url can have the form of [https://solscan.io/token/{token_mint}](https://solscan.io/token/%7Btoken_mint%7D), e.g. https://solscan.io/token/993dVFL2uXWYeoXuEBFXR4BijeXdTv4s6BzsCjJZuwqk for cUSDC @stevenhansel

Sure, please check it out again @vantessel

2022-11-14 13:35 UTC, vantessel commented
lgtm!

2022-11-14 13:59 UTC, thegreat-vanderlinde requested changes
overall looks like a great implementation, can you just please fix the url as per the comment below?

2022-11-14 13:59 UTC, thegreat-vanderlinde commented on src/components/molecules/CoinBadge/CoinBadge.tsx
> +			<a href={`${solscan.baseUrl}/token/${props.token.address}`} target="_blank" rel="noopener noreferrer" className={styles.chip}>
Can we use the library `@vyper-protocol/explorer-link-helper`? It's already in place somewhere in the project. The library currently supports `tx` and `account`, in this case we can treat the mint address as an account. 

Apparently on solscan the following urls redirect to the same:
- https://solscan.io/token/993dVFL2uXWYeoXuEBFXR4BijeXdTv4s6BzsCjJZuwqk
- https://solscan.io/account/993dVFL2uXWYeoXuEBFXR4BijeXdTv4s6BzsCjJZuwqk

We can harcode solscan as the preferred explorer (maybe in the future we can make it selectable as a user preference) and we can inject the current cluster from the `env`.

2022-11-14 14:17 UTC, stevenhansel commented on src/components/molecules/CoinBadge/CoinBadge.tsx
> +			<a href={`${solscan.baseUrl}/token/${props.token.address}`} target="_blank" rel="noopener noreferrer" className={styles.chip}>
Done! @thegreat-vanderlinde please check my newest commit, thanks!

2022-11-14 14:39 UTC, thegreat-vanderlinde approved these changes
perfect!

2022-11-14 14:40 UTC, merged