312-explorer-filters
vyper-protocol/vyper-otc-ui pull request #374
Opened 2022-11-22 12:59 UTC by stevenhansel

2022-11-28 14:20 UTC, thegreat-vanderlinde requested changes
overall this is amazing, exactly as we had in mind. Just left a couple of comments to cover. In addition can we replace the default explorer link with a query with the `settle_available_from` in the last 5 days? Should be `explorer?settleAvailableFromAt=2022-11-23T00%3A00+after&page=1&limit=25` so by the default navigating to the explorer should present the same behavior as before

2022-11-28 14:20 UTC, thegreat-vanderlinde commented on src/controllers/fetchContracts/FetchContractsParams.ts
>  		r.gte.push({ column: 'settle_available_from', value: nd.toUTCString() });
we can remove now the fixed 5day filter

2022-11-28 14:20 UTC, thegreat-vanderlinde commented on src/controllers/fetchContracts/FetchContractsParams.ts
>  		r.eq.push({ column: 'cluster', value: cluster });
do you think can make sense to move this on a lower level? for example during supabase query creation

2022-11-28 15:03 UTC, vantessel commented on src/controllers/fetchContracts/FetchContractsParams.ts
> +export const toSupabaseColumn = (key: string): string | null => {
can we please rename the parameters to something more intuitive from the outside, for example:

- `redeemLogicState.typeId` -> `payoff`
- `redeemLogicState.notional` -> `notional`
- `redeemLogicState.strike` -> `strike`
- `settleAvailableFromAt` -> `expiry`

2022-11-28 15:06 UTC, thegreat-vanderlinde commented
@stevenhansel seems on mainnet the explorer is not working

https://deploy-preview-374--vyper-otc-mainnet-stag.netlify.app/explorer

2022-11-28 15:18 UTC, stevenhansel commented on src/controllers/fetchContracts/FetchContractsParams.ts
>  		r.eq.push({ column: 'cluster', value: cluster });
Just to make sure, does this mean that you want to move the cluster filter to `selectContracts()` (`/api/supabase/selectContracts.ts`) ? @thegreat-vanderlinde

2022-11-28 15:19 UTC, stevenhansel commented on src/controllers/fetchContracts/FetchContractsParams.ts
> +export const toSupabaseColumn = (key: string): string | null => {
Yes, I believe that we can do that. I will make the changes in the future commits

2022-11-28 15:20 UTC, stevenhansel commented
> @stevenhansel seems on mainnet the explorer is not working
> 
> https://deploy-preview-374--vyper-otc-mainnet-stag.netlify.app/explorer

Just realized about this. I think it's happening every time when there is no data (`rowCount == 0`). I will try to find a fix regarding this

2022-11-29 02:42 UTC, stevenhansel commented
@thegreat-vanderlinde About the issue with the data grid not showing anything when there are no rows, it's actually the expected behavior of the data grid itself. What we can do is that adding a component overlay when there are no results using `NoResultsOverlay`, https://mui.com/x/api/data-grid/data-grid/#slots. Let me know what you think.

Other than that, I have resolved the other comments, please check the latest commit. Thanks!

2022-11-29 08:56 UTC, thegreat-vanderlinde commented on src/controllers/fetchContracts/FetchContractsParams.ts
>  		r.eq.push({ column: 'cluster', value: cluster });
yes exactly

2022-11-29 08:58 UTC, thegreat-vanderlinde commented
> @thegreat-vanderlinde About the issue with the data grid not showing anything when there are no rows, it's actually the expected behavior of the data grid itself. What we can do is that adding a component overlay when there are no results using `NoResultsOverlay`, https://mui.com/x/api/data-grid/data-grid/#slots. Let me know what you think.
> 
> Other than that, I have resolved the other comments, please check the latest commit. Thanks!

Yes please, let's add the component if there's no result in the datagrid, will definitely improve UX

2022-11-29 15:18 UTC, vantessel approved these changes
lgtm thx

2022-11-30 14:21 UTC, stevenhansel commented on src/components/organisms/ExplorerContractDataGrid/ExplorerContractDataGrid.tsx
>  			{contracts.length > 0 && (
@thegreat-vanderlinde Just realized when debugging the HTML in the component tree that the <main> tag doesn't have any children. Turns out the data grid was gone because of a simple conditional. I included the fix in the newest commit

2022-12-01 09:44 UTC, thegreat-vanderlinde commented on src/components/organisms/ExplorerContractDataGrid/ExplorerContractDataGrid.tsx
>  			{contracts.length > 0 && (
lol this is a great news btw

2022-12-02 11:13 UTC, thegreat-vanderlinde approved these changes

2022-12-02 11:13 UTC, merged