345 - Create abstract publickey selector
vyper-protocol/vyper-otc-ui pull request #485
Opened 2022-12-12 06:00 UTC by Shikhar15606

Fix #345

2022-12-12 18:00 UTC, thegreat-vanderlinde requested changes

2022-12-12 18:00 UTC, thegreat-vanderlinde commented on src/components/molecules/OraclesPicker/OraclesPicker.tsx
> +					free={currentCluster === 'devnet'}
can we mantain the same mui naming here with `freeSolo`?

2022-12-12 18:00 UTC, thegreat-vanderlinde commented on src/components/molecules/OraclesPicker/OraclesPicker.tsx
> +					publicKeyLabels={options.map((o) => ({
can we rename the property from `publicKeyLabels` to `availableOptions` for consistency?

2022-12-12 18:07 UTC, Shikhar15606 commented on src/components/molecules/OraclesPicker/OraclesPicker.tsx
> +					free={currentCluster === 'devnet'}
Ya sure

2022-12-12 18:07 UTC, Shikhar15606 commented on src/components/molecules/OraclesPicker/OraclesPicker.tsx
> +					publicKeyLabels={options.map((o) => ({
that would be better

2022-12-13 07:47 UTC, thegreat-vanderlinde approved these changes
lgtm

2022-12-13 07:47 UTC, merged