364 refactor featured products pages
vyper-protocol/vyper-otc-ui pull request #507
Opened 2022-12-16 17:29 UTC by vantessel

fix #495 
fix #478 
fix #466

2022-12-19 15:56 UTC, thegreat-vanderlinde requested changes
not sure if it has been introduced with this PR but we have a lot of errors in the console:
![Screenshot 2022-12-19 at 16 52 31](https://user-images.githubusercontent.com/91868385/208466345-f677d7dd-dcdf-4762-81f7-80291cef9ed4.png)

they seems triggered on a regular schedule.

we should investigate if we're throwing them in a timer or they're triggered by trading view component (in that case we could eventually investigate if it's possible to suppress)

2022-12-19 15:56 UTC, thegreat-vanderlinde commented on src/pages/contract/featured/sol-10x/index.tsx
> +	}, [showRfq, rfqLoading, pricesValue]);
would change this logic in a more readble version, like:
```ts
const onRfqButtonClick = async () => {
		setRfqLoading(true);

		try {
			await sleep(1500);

			setSettleStart(refSettle());
			setRfqStrike(BSDigitalStrike(pricesValue[0], 0, 3.5, 1 / 24 / 365, true, 0.1));
			if (!showRfq) {
				setShowRfq(true);
			}
		} finally {
			setRfqProgress(100);
			setRfqLoading(false);
		}
	};
```

`sleep` is from `utils/sleep`

2022-12-19 15:56 UTC, thegreat-vanderlinde commented on src/pages/contract/featured/sol-10x/index.tsx
> +	}, [rfqProgress]);
using `setInterval` in a `useEffect` is usually dangerous. Having the `rfqProgress` as a dependency and changing it in the timer body will create a new timer on each tick (you can try to console log the timer id on line 83 to notice the new id every time). 

A better solution could be to start the timer at the page mount (empty array as `useEffect` dependency) and simply decreasing the progress value everytime:
```ts
useEffect(() => {
		const timer = setInterval(() => {
			setRfqProgress((oldProgress) => {
				return Math.max(0, oldProgress - 100 / 120);
			});
		}, 500);
		return () => clearInterval(timer);
	}, []);
```

this should work fine, having the rfqProgress reset to 100 on the button click

2022-12-19 18:26 UTC, vantessel commented
The errors seem to be triggered by the loading of an external script from [tradingview](https://www.tradingview.com/widget/advanced-chart/). I tried embedding directly but I see the same errors. I didn't find an easy way to suppress them, any suggestion?

Same error [here](https://k-128.github.io/react-tradingview-embed/?path=/story/widgets--advanced-chart-story)

2022-12-20 09:33 UTC, thegreat-vanderlinde commented
> The errors seem to be triggered by the loading of an external script from [tradingview](https://www.tradingview.com/widget/advanced-chart/). I tried embedding directly but I see the same errors. I didn't find an easy way to suppress them, any suggestion?
> 
> Same error [here](https://k-128.github.io/react-tradingview-embed/?path=/story/widgets--advanced-chart-story)

I tried to investigate a little, but haven't found anything viable. for now we can ignore and merge as is

2022-12-20 17:55 UTC, merged