55 - Basic Create Contract page
vyper-protocol/vyper-otc-ui pull request #57
Opened 2022-09-27 16:06 UTC by thegreat-vanderlinde

Basic hidden "create contract" page to skip using mercato libero

Close #55

2022-09-28 17:24 UTC, GnosisAssembler commented on src/pages/contract/create/index.tsx
> +	const [depositStart, setDepositStart] = useState(moment.duration(0, 'minutes').asMilliseconds());
Here we should initialize the state with an initial value and set the state value as soon as the component is being rendered as follows. 

```js
useEffect(()=>{
  setDepositStart(moment.duration(0, 'minutes').asMilliseconds())
},[ ])
```

This is a good practice in order to avoid `hydration` errors, that cause the first chunk of the code to be different than the following chunks when re-renders are being executed. 
Generally `hydration` errors are degrading the performance.

2022-09-28 18:04 UTC, thegreat-vanderlinde commented on src/components/organisms/TopBar/TopBar.tsx
> -	},
I moved outside the buttons array for custom click behavior

2022-09-28 20:32 UTC, thegreat-vanderlinde commented on src/pages/contract/create/index.tsx
> +	const [depositStart, setDepositStart] = useState(moment.duration(0, 'minutes').asMilliseconds());
Don't completely agree on this, using 
```ts
	const [depositStart, setDepositStart] = useState(moment.duration(0, 'minutes').asMilliseconds());
	const [depositEnd, setDepositEnd] = useState(moment.duration(5, 'minutes').asMilliseconds());
	const [settleStart, setSettleStart] = useState(moment.duration(15, 'minutes').asMilliseconds());
```
is exactly the same as using
```ts
	const [depositStart, setDepositStart] = useState(0);
	const [depositEnd, setDepositEnd] = useState(300000); // 5min in ms -> 5*60*1000
	const [settleStart, setSettleStart] = useState(900000); // 15min in ms -> 15*60*1000
```
so having constants values shouldn't be the same for all re-redendering?

2022-09-29 09:17 UTC, GnosisAssembler commented on src/pages/contract/create/index.tsx
> +	const [depositStart, setDepositStart] = useState(moment.duration(0, 'minutes').asMilliseconds());
Yes of course it is the same.

The problem is that in the first case, the `depositStart` takes slightly more time to be initialized, which is of course not much. But we are passing `depositStart`, formatted with the moment method, as a value to the component `DurationPicker` and then the `DurationPicker` passes  the value again to Evergreen's `TextField`, using moment once more. 

This whole process (which is slightly slower than just initializing a plain number), causes the evergreen's `TextField` component to have a mismatched value, when React checks the first content rendered and the next one right after. 

In my understanding this is happening only with mismatched values in props of components than belong to external libraries (in our case Evergreen), that take slightly more time to load (during the import statement). A solution for that maybe would be to also use a `dynamic import`. 

Also i am guessing that **Next.js** has to do something with those hydration errors, because i have encountered them very often when we have started the development of this project with **Next.js**. Maybe it is because it uses `ReactDOMServer` in the background, in some way. 
Hydration errors seems to originate exactly for this reason actually, when `React expects that the rendered content is identical between the server and the client` (meaning ReactDOM and ReactDOMServer).

And it's weird cause the docs say that hydration errors are very rare and make sense to be rare tbh. We are initializing a tone of complex `useState` hooks in other projects, that dont use Next.js and we have never seen that before.  

The `useEffect` workaround resolved the errors for me, though.

2022-09-29 09:30 UTC, thegreat-vanderlinde commented on src/pages/contract/create/index.tsx
> +	const [depositStart, setDepositStart] = useState(moment.duration(0, 'minutes').asMilliseconds());
will use the `useEffect` workaround for now, then when we'll create the ultimate page we'll check it better

2022-09-29 09:39 UTC, GnosisAssembler requested changes

2022-09-29 09:39 UTC, GnosisAssembler commented on src/pages/contract/create/index.tsx
> +	useEffect(() => {
Here we can use only one `useEffect` with all the three `set` statements inside, as the hook runs only once.

2022-09-29 09:42 UTC, GnosisAssembler approved these changes
LGTM

2022-09-29 10:34 UTC, merged