49 - add social links in top bar menu
vyper-protocol/vyper-otc-ui pull request #64
Opened 2022-09-29 18:54 UTC by stevenhansel

![Screen Shot 2022-09-30 at 01 53 24](https://user-images.githubusercontent.com/54180475/193118155-2002a96b-397d-45fc-874f-71bc0207c79f.png)

- Added twitter and discord icon in the top bar menu for now

Notes:
1. Icons downloaded from https://simpleicons.org/ (all icons are licensed with CC0)
2. To make importing SVG easier, I'm using: https://react-svgr.com/playground/?typescript=true which convert the contents of a SVG file to a JSX Element

2022-09-29 19:33 UTC, GnosisAssembler requested changes

2022-09-29 19:33 UTC, GnosisAssembler commented on src/components/atoms/Icons/Discord.tsx
> +import { SVGProps } from 'react';
I think it's better to just use this library [React Icons](https://react-icons.github.io/react-icons/), which provides all the icons as independent React Components.

No need to create our own icon Components, for now.

2022-09-30 01:57 UTC, stevenhansel commented
@GnosisAssembler I have pushed a new commit with the adjustment you commented above, please re-check it, thanks!

2022-09-30 07:23 UTC, thegreat-vanderlinde commented
@GnosisAssembler can you please review changes and then resolve conversations?

2022-09-30 08:18 UTC, GnosisAssembler approved these changes
looks really good

2022-09-30 08:44 UTC, thegreat-vanderlinde requested changes

2022-09-30 08:44 UTC, thegreat-vanderlinde commented on src/components/atoms/Icon/Icon.tsx
> +export default Icon;
Importing the icon components one by one can lead to future errors when someone upgrade the json source file but forget to import the correct icon here, a more flexible refactor could be converting the `Props.name` to a plain string and using it as key accessor for the library, something like:

```ts
import { IconBaseProps } from 'react-icons';
import * as icon from 'react-icons/fa';

type Props = {
	name: string;
} & IconBaseProps;

const Icon = (props: Props) => {
	const { name, ...rest } = props;

	const SvgComponent = icon[name];
	return <SvgComponent {...rest} />;
};

export default Icon;
```

following this pattern we can just choose the icon in json file and forget the rest.

The only concern of this option is the final bundle size importing all the icons `import * as icon from 'react-icons/fa';`. @stevenhansel can you do a fast check if it's affected?

2022-09-30 08:44 UTC, thegreat-vanderlinde commented on src/configs/resources.json
> +}
we need also the following:
- Main website: https://www.vyperprotocol.io/
- Medium: https://vyperprotocol.medium.com/
- Github: https://github.com/vyper-protocol
- Docs: https://docs.vyperprotocol.io/

2022-09-30 09:00 UTC, GnosisAssembler commented on src/components/atoms/Icon/Icon.tsx
> +export default Icon;
Definitely agree, with the errors regarding the update of both the `src` and the `json`. 

However we cannot do that
```js
import * as icon from 'react-icons/fa';
```
because [React Icons](https://react-icons.github.io/react-icons/) have several libraries of icons that u can import. 
```js
import * as icon from 'react-icons/fa';
import * as icon from 'react-icons/bs';
import * as icon from 'react-icons/fi';
import * as icon from 'react-icons/cl';
// ... etc etc
```

Maybe for the shake of simplicity (because we do not have our own dedicated icon library right now anyways), we can just import only the icons we want, right inside the file, and use them as Components. 

```js
import { DiscordIcon } from "react-icons/fa";

<DiscordIcon />
```

We can still pass props to this React-icon component. React icons is very versatile.

2022-09-30 09:13 UTC, stevenhansel commented on src/components/atoms/Icon/Icon.tsx
> +export default Icon;
That sounds like a great idea, I think while on that I will also work on the issue to integrate the bundle analyzer into the project #69 so I can check how impactful importing all the icons will be

2022-09-30 09:21 UTC, thegreat-vanderlinde commented on src/components/atoms/Icon/Icon.tsx
> +export default Icon;
I like @stevenhansel `Icon` solution, let's stick with that and for only support `Fa` icons importing just `import * as icon from 'react-icons/fa';` so we can declare icon id in the json.

Once we'll get on #69 we can check how importing `*` can affect on bundle size. Let's keep things simple for this PR

2022-09-30 10:09 UTC, stevenhansel commented on src/components/atoms/Icon/Icon.tsx
> +export default Icon;
> I like @stevenhansel `Icon` solution, let's stick with that and for now only support `Fa` icons using `import * as icon from 'react-icons/fa';` so we can declare icon id in the json.
> 
> Once we'll get on #69 we can check how importing `*` can affect on bundle size. Let's keep things simple for this PR

Okay, I think I'll install the bundler and check the differences between importing all icons and not, I'll publish the results here once I finish working at #69

2022-09-30 12:46 UTC, stevenhansel commented
@thegreat-vanderlinde @GnosisAssembler I have finished running the bundler analyzer and here are the results:

The current implementation's bundle size:
<img width="1439" alt="Screen Shot 2022-09-30 at 19 41 01" src="https://user-images.githubusercontent.com/54180475/193272536-3a21741e-671c-4ff8-b554-2f7e0519d7c3.png">

Using `import * as icons from 'react-icons/fa'`
<img width="1433" alt="Screen Shot 2022-09-30 at 19 43 21" src="https://user-images.githubusercontent.com/54180475/193272577-84ba5000-bf00-4f4f-b621-f1f5b016d805.png">

There's almost a 1MB difference in the bundle size, so I think it's better we avoid importing all the icons

2022-09-30 13:52 UTC, thegreat-vanderlinde commented
@stevenhansel thanks for the detailed analysis, 1MB increase in bundle size is way more than I expected. Let's stick with your solution in order to have a lighter bundle

2022-09-30 13:53 UTC, merged