37  - Cluster selector
vyper-protocol/vyper-otc-ui pull request #94
Opened 2022-10-03 17:27 UTC by GnosisAssembler

- Created cluster selection modal
- Created `useCluster` hook in order to retrieve cluster param from the URL

_Currently the default cluster is **devnet** we are sill in development _

2022-10-04 08:49 UTC, thegreat-vanderlinde requested changes

2022-10-04 08:49 UTC, thegreat-vanderlinde commented on src/components/molecules/SearchBar/SearchBar.tsx
> +					router.push(`/contract/summary/${searchState.value}?cluster=${cluster}`);
can we create a custom method to build url? so we don't have to spread around the project all the hard coded urls? in that method we'gonna use the `const { cluster } = useCluster();`. That way the SearchBar will remain cleaner and more readable

2022-10-04 08:49 UTC, thegreat-vanderlinde commented on src/components/molecules/SearchBar/SearchBar.tsx
> +					router.push(`/contract/summary/${searchState.value}?cluster=${cluster}`);
we should avoid building URL with search params by hand, we should use the `URL` type, more on that [here](https://www.valentinog.com/blog/url/#how-to-build-an-url-and-its-search-parameters).

2022-10-04 08:49 UTC, thegreat-vanderlinde commented on src/components/organisms/ClusterSelector/ClusterSelector.tsx
> +	]);
why using `useState` here?

2022-10-04 08:49 UTC, thegreat-vanderlinde commented on src/components/organisms/ClusterSelector/ClusterSelector.tsx
> +	]);
the available clusters should be read from the dedicated json file, not hardcoded here

2022-10-04 08:49 UTC, thegreat-vanderlinde commented on src/components/organisms/ClusterSelector/ClusterSelector.tsx
> +			router.push(router.asPath.split('?')[0] + '?cluster=' + event.target.value);
again we should avoid managing urls as plain string, this is super error-prone. use the `URL` type

2022-10-04 08:49 UTC, thegreat-vanderlinde commented on src/components/organisms/TopBar/TopBar.tsx
> +			}
we should avoid declaring the cluster everytime we push a new route, this can be easily forgot. we have to build new routes in a dedicated method/helper so the caller can avoid declaring the cluster, and at url building time we can set the current selected cluster

2022-10-04 08:49 UTC, thegreat-vanderlinde commented on src/hooks/useGetFetchOTCStateQuery.ts
> +		['otc-state', otcState, cluster],
1. avoid using the type `any`
2. we should probably step back to the basis: the only objective of the cluster is to select the chain connection, `devnet` set the connection to rpc url `https://api.devnet.solana.com` for example. the connection is the main info stored inside the `provider: AnchorProvider`, so passing both the info to this method have no sense. we have to remove the cluster param and add the `provider.connection` to the `useQuery` array first param

2022-10-04 08:49 UTC, thegreat-vanderlinde commented on src/pages/contract/summary/[id].tsx
> +// localhost:3000/contract/summary/5sEVKL6WpGjXSnQyvgurys8QbUmho1ia77pyEsXP2Vzk?cluster=mainnet-beta
we have nothing deployed on mainnet yet

2022-10-04 16:19 UTC, GnosisAssembler commented on src/hooks/useGetFetchOTCStateQuery.ts
> +		['otc-state', otcState, cluster],
makes sense. My bad.

2022-10-05 14:30 UTC, thegreat-vanderlinde commented
@GnosisAssembler can you please resolve conflicts?

2022-10-05 16:56 UTC, thegreat-vanderlinde submitted a review, later dismissed

2022-10-05 16:58 UTC, thegreat-vanderlinde approved these changes

2022-10-05 16:58 UTC, merged